version: '2'
services:
  web:
    container_name: cuteone
    image: hulb/cuteone:latest
    ports:
      - 5000:5000
    links:
      - mysql:mysql
      - mongo:mongo
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cuteone
      - MYSQL_ROOT_PASSWORD=cuteone
      - MYSQL_USER=root
    volumes:
      - /root/cuteone/mysql:/var/lib/mysql
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /root/cuteone/mongo:/data/db
